/** Theme color tokens as CSS variables — resolve at runtime for light/dark */
export const BLUE     = 'var(--accent)'
export const BLUE2    = 'var(--accent-h)'
export const WARM     = 'var(--warm)'
export const INK      = 'var(--ink-primary)'
export const INK_BODY = 'var(--ink-body)'
export const INK_SEC  = 'var(--ink-secondary)'
export const INK_TERT = 'var(--ink-tertiary)'
export const BORDER   = 'var(--border)'
export const SURF0    = 'var(--surface-0)'
export const SURF1    = 'var(--surface-1)'
export const SURF2    = 'var(--surface-2)'
export const SURF3    = 'var(--surface-3)'
export const OVERLAY  = 'var(--overlay-scrim)'
export const ACCENT_MUTED = 'var(--accent-muted)'
